Player board class
nolasemon/pts24-python-wonderful-team pull request #22
Opened 2024-11-23 21:56 UTC by genusB

2024-11-23 22:51 UTC, MorShow approved these changes
Nice implementation of Player board class, but now we have some merge conflicts..

2024-11-26 08:33 UTC, nolasemon requested changes

2024-11-26 08:33 UTC, nolasemon commented on stone_age/player_board/player_tools.py
> +        return f"Tools: {self._tools}, used: {self._used_tools}"
```suggestion
        raise NotImplementedError
```
Tests will still pass because of Mock

2024-11-26 08:33 UTC, nolasemon commented on stone_age/player_board/player_tools.py
> +    def get_tool_count(self) -> int:
I would suggest sticking to getters without get_ prefix as currently it is predominant approach in this project.
```suggestion
    def tool_count(self) -> int:
```

2024-11-26 08:33 UTC, nolasemon commented on stone_age/player_board/tribe_fed_status.py
> +    def get_fields(self) -> int:
```suggestion
    def fields(self) -> int:
```

2024-11-26 08:33 UTC, nolasemon commented on stone_age/player_board/tribe_fed_status.py
> +        return f"Tribe fed: {self._tribe_fed}, fields: {self._fields}"
```suggestion
        raise NotImplementedError
```

2024-11-26 08:33 UTC, nolasemon commented on stone_age/player_board/player_board.py
> +            self._fed_status.get_fields,
```suggestion
            self._tools.tool_count,
            self._fed_status.fields,
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.assertIn("Houses: 0", state)
```suggestion
        self.assertIn('"points": 0', state)
        self.assertIn('"houses": 0', state)
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.assertIn("Points: 8", self.board.state())
```suggestion
        self.board.add_points(5)
        self.assertIn('"points": 5', self.board.state())
        self.board.add_points(3)
        self.assertIn('"points": 8', self.board.state())
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.assertIn("Houses: 2", self.board.state())
```suggestion
        self.board.add_house()
        self.assertIn('"houses": 1', self.board.state())
        self.board.add_house()
        self.assertIn('"houses": 2', self.board.state())
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.fed_status.get_fields.return_value = 4
```suggestion
        self.tools.tool_count.return_value = 3
        self.fed_status.fields.return_value = 4
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.assertIn("Points: 30", self.board.state())
```suggestion
        self.assertIn('"points": 30', self.board.state())
```

2024-11-26 08:33 UTC, nolasemon commented on test/player_board/test_player_board.py
> +        self.assertIn("Points: 18", self.board.state())
```suggestion
        self.assertIn('"points": 18', self.board.state())
```

2024-11-26 11:07 UTC, genusB reviewed
Changes resolved

2024-11-26 12:46 UTC, nolasemon approved these changes

2024-11-26 17:21 UTC, merged